// GLES enums used internally that WebGL itself does not expose.
export const GLX = {
  EXTENSIONS: 0x1f03,
  NUM_COMPRESSED_TEXTURE_FORMATS: 0x86a2,
  INFO_LOG_LENGTH: 0x8b84,
  ACTIVE_UNIFORM_MAX_LENGTH: 0x8b87,
  ACTIVE_ATTRIBUTE_MAX_LENGTH: 0x8b8a,
  NUM_SAMPLE_COUNTS: 0x9380,
  TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH: 0x8c76,
  UNIFORM_BLOCK_NAME_LENGTH: 0x8a41,
  TIMEOUT_IGNORED: -1,
} as const;
