// getParameter() return-type table (WebGL 1 + 2 + extension pnames).
import { GL } from './constants.ts';

export type ParamKind =
  | 'bool' | 'int' | 'uint' | 'float' | 'int64' | 'string'
  | 'i32x2' | 'i32x4' | 'f32x2' | 'f32x4' | 'boolx4' | 'compressed'
  | 'buffer' | 'texture' | 'framebuffer' | 'renderbuffer' | 'program' | 'vao' | 'sampler' | 'tf';

const P = new Map<number, ParamKind>();
const set = (kind: ParamKind, ...names: number[]) => { for (const n of names) P.set(n, kind); };

// --- WebGL 1 -----------------------------------------------------------------
set('uint', GL.ACTIVE_TEXTURE, GL.BLEND_DST_ALPHA, GL.BLEND_DST_RGB, GL.BLEND_EQUATION_ALPHA, GL.BLEND_EQUATION_RGB,
  GL.BLEND_SRC_ALPHA, GL.BLEND_SRC_RGB, GL.CULL_FACE_MODE, GL.DEPTH_FUNC, GL.FRONT_FACE, GL.GENERATE_MIPMAP_HINT,
  GL.IMPLEMENTATION_COLOR_READ_FORMAT, GL.IMPLEMENTATION_COLOR_READ_TYPE, GL.STENCIL_BACK_FAIL, GL.STENCIL_BACK_FUNC,
  GL.STENCIL_BACK_PASS_DEPTH_FAIL, GL.STENCIL_BACK_PASS_DEPTH_PASS, GL.STENCIL_FAIL, GL.STENCIL_FUNC,
  GL.STENCIL_PASS_DEPTH_FAIL, GL.STENCIL_PASS_DEPTH_PASS, GL.STENCIL_BACK_VALUE_MASK, GL.STENCIL_BACK_WRITEMASK,
  GL.STENCIL_VALUE_MASK, GL.STENCIL_WRITEMASK, GL.UNPACK_COLORSPACE_CONVERSION_WEBGL);
set('f32x2', GL.ALIASED_LINE_WIDTH_RANGE, GL.ALIASED_POINT_SIZE_RANGE, GL.DEPTH_RANGE);
set('int', GL.ALPHA_BITS, GL.BLUE_BITS, GL.GREEN_BITS, GL.RED_BITS, GL.DEPTH_BITS, GL.STENCIL_BITS,
  GL.MAX_COMBINED_TEXTURE_IMAGE_UNITS, GL.MAX_CUBE_MAP_TEXTURE_SIZE, GL.MAX_FRAGMENT_UNIFORM_VECTORS,
  GL.MAX_RENDERBUFFER_SIZE, GL.MAX_TEXTURE_IMAGE_UNITS, GL.MAX_TEXTURE_SIZE, GL.MAX_VARYING_VECTORS,
  GL.MAX_VERTEX_ATTRIBS, GL.MAX_VERTEX_TEXTURE_IMAGE_UNITS, GL.MAX_VERTEX_UNIFORM_VECTORS, GL.PACK_ALIGNMENT,
  GL.UNPACK_ALIGNMENT, GL.SAMPLE_BUFFERS, GL.SAMPLES, GL.STENCIL_BACK_REF, GL.STENCIL_CLEAR_VALUE, GL.STENCIL_REF,
  GL.SUBPIXEL_BITS);
set('buffer', GL.ARRAY_BUFFER_BINDING, GL.ELEMENT_ARRAY_BUFFER_BINDING);
set('bool', GL.BLEND, GL.CULL_FACE, GL.DEPTH_TEST, GL.DEPTH_WRITEMASK, GL.DITHER, GL.POLYGON_OFFSET_FILL,
  GL.SAMPLE_ALPHA_TO_COVERAGE, GL.SAMPLE_COVERAGE, GL.SAMPLE_COVERAGE_INVERT, GL.SCISSOR_TEST, GL.STENCIL_TEST,
  GL.UNPACK_FLIP_Y_WEBGL, GL.UNPACK_PREMULTIPLY_ALPHA_WEBGL);
set('f32x4', GL.BLEND_COLOR, GL.COLOR_CLEAR_VALUE);
set('boolx4', GL.COLOR_WRITEMASK);
set('compressed', GL.COMPRESSED_TEXTURE_FORMATS);
set('program', GL.CURRENT_PROGRAM);
set('float', GL.DEPTH_CLEAR_VALUE, GL.LINE_WIDTH, GL.POLYGON_OFFSET_FACTOR, GL.POLYGON_OFFSET_UNITS, GL.SAMPLE_COVERAGE_VALUE);
set('framebuffer', GL.FRAMEBUFFER_BINDING);
set('i32x2', GL.MAX_VIEWPORT_DIMS);
set('renderbuffer', GL.RENDERBUFFER_BINDING);
set('string', GL.RENDERER, GL.SHADING_LANGUAGE_VERSION, GL.VENDOR, GL.VERSION);
set('i32x4', GL.SCISSOR_BOX, GL.VIEWPORT);
set('texture', GL.TEXTURE_BINDING_2D, GL.TEXTURE_BINDING_CUBE_MAP);

// --- WebGL 2 -----------------------------------------------------------------
set('buffer', GL.COPY_READ_BUFFER_BINDING, GL.COPY_WRITE_BUFFER_BINDING, GL.PIXEL_PACK_BUFFER_BINDING,
  GL.PIXEL_UNPACK_BUFFER_BINDING, GL.TRANSFORM_FEEDBACK_BUFFER_BINDING, GL.UNIFORM_BUFFER_BINDING);
set('framebuffer', GL.DRAW_FRAMEBUFFER_BINDING, GL.READ_FRAMEBUFFER_BINDING);
set('uint', GL.FRAGMENT_SHADER_DERIVATIVE_HINT, GL.READ_BUFFER);
for (let i = 0; i < 16; i++) P.set(GL.DRAW_BUFFER0 + i, 'uint');
set('int', GL.MAX_3D_TEXTURE_SIZE, GL.MAX_ARRAY_TEXTURE_LAYERS, GL.MAX_COLOR_ATTACHMENTS, GL.MAX_COMBINED_UNIFORM_BLOCKS,
  GL.MAX_DRAW_BUFFERS, GL.MAX_ELEMENTS_INDICES, GL.MAX_ELEMENTS_VERTICES, GL.MAX_FRAGMENT_INPUT_COMPONENTS,
  GL.MAX_FRAGMENT_UNIFORM_BLOCKS, GL.MAX_FRAGMENT_UNIFORM_COMPONENTS, GL.MAX_PROGRAM_TEXEL_OFFSET,
  GL.MIN_PROGRAM_TEXEL_OFFSET, GL.MAX_SAMPLES, GL.MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS,
  GL.MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS, GL.MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS,
  GL.MAX_UNIFORM_BUFFER_BINDINGS, GL.MAX_VARYING_COMPONENTS, GL.MAX_VERTEX_OUTPUT_COMPONENTS,
  GL.MAX_VERTEX_UNIFORM_BLOCKS, GL.MAX_VERTEX_UNIFORM_COMPONENTS, GL.UNIFORM_BUFFER_OFFSET_ALIGNMENT,
  GL.PACK_ROW_LENGTH, GL.PACK_SKIP_PIXELS, GL.PACK_SKIP_ROWS, GL.UNPACK_IMAGE_HEIGHT, GL.UNPACK_ROW_LENGTH,
  GL.UNPACK_SKIP_IMAGES, GL.UNPACK_SKIP_PIXELS, GL.UNPACK_SKIP_ROWS);
set('float', GL.MAX_TEXTURE_LOD_BIAS);
set('int64', GL.MAX_CLIENT_WAIT_TIMEOUT_WEBGL, GL.MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS,
  GL.MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS, GL.MAX_ELEMENT_INDEX, GL.MAX_SERVER_WAIT_TIMEOUT, GL.MAX_UNIFORM_BLOCK_SIZE);
set('bool', GL.RASTERIZER_DISCARD, GL.TRANSFORM_FEEDBACK_ACTIVE, GL.TRANSFORM_FEEDBACK_PAUSED);
set('sampler', GL.SAMPLER_BINDING);
set('texture', GL.TEXTURE_BINDING_2D_ARRAY, GL.TEXTURE_BINDING_3D);
set('tf', GL.TRANSFORM_FEEDBACK_BINDING);
set('vao', GL.VERTEX_ARRAY_BINDING);

// --- Extensions ---------------------------------------------------------------
export const EXT_PNAME = {
  MAX_TEXTURE_MAX_ANISOTROPY_EXT: 0x84ff,
  FRAGMENT_SHADER_DERIVATIVE_HINT_OES: 0x8b8b,
  VERTEX_ARRAY_BINDING_OES: 0x85b5,
  MAX_COLOR_ATTACHMENTS_WEBGL: 0x8cdf,
  MAX_DRAW_BUFFERS_WEBGL: 0x8824,
  UNMASKED_VENDOR_WEBGL: 0x9245,
  UNMASKED_RENDERER_WEBGL: 0x9246,
  TIMESTAMP_EXT: 0x8e28,
  GPU_DISJOINT_EXT: 0x8fbb,
  MAX_VIEWS_OVR: 0x9631,
  MAX_CLIP_DISTANCES_WEBGL: 0x0d32,
  MAX_CULL_DISTANCES_WEBGL: 0x82f9,
  MAX_COMBINED_CLIP_AND_CULL_DISTANCES_WEBGL: 0x82fa,
  MAX_DUAL_SOURCE_DRAW_BUFFERS_WEBGL: 0x88fc,
  PROVOKING_VERTEX_WEBGL: 0x8e4f,
  CLIP_ORIGIN_EXT: 0x935c,
  CLIP_DEPTH_MODE_EXT: 0x935d,
  POLYGON_OFFSET_CLAMP_EXT: 0x8e1b,
  POLYGON_MODE_WEBGL: 0x0b40,
} as const;

set('float', EXT_PNAME.MAX_TEXTURE_MAX_ANISOTROPY_EXT, EXT_PNAME.POLYGON_OFFSET_CLAMP_EXT);
set('uint', EXT_PNAME.FRAGMENT_SHADER_DERIVATIVE_HINT_OES, EXT_PNAME.PROVOKING_VERTEX_WEBGL, EXT_PNAME.CLIP_ORIGIN_EXT,
  EXT_PNAME.CLIP_DEPTH_MODE_EXT, EXT_PNAME.POLYGON_MODE_WEBGL);
set('vao', EXT_PNAME.VERTEX_ARRAY_BINDING_OES);
set('int', EXT_PNAME.MAX_COLOR_ATTACHMENTS_WEBGL, EXT_PNAME.MAX_DRAW_BUFFERS_WEBGL, EXT_PNAME.MAX_VIEWS_OVR,
  EXT_PNAME.MAX_CLIP_DISTANCES_WEBGL, EXT_PNAME.MAX_CULL_DISTANCES_WEBGL, EXT_PNAME.MAX_COMBINED_CLIP_AND_CULL_DISTANCES_WEBGL,
  EXT_PNAME.MAX_DUAL_SOURCE_DRAW_BUFFERS_WEBGL);
set('string', EXT_PNAME.UNMASKED_VENDOR_WEBGL, EXT_PNAME.UNMASKED_RENDERER_WEBGL);
set('int64', EXT_PNAME.TIMESTAMP_EXT);
set('bool', EXT_PNAME.GPU_DISJOINT_EXT);

export const PARAMETER_KINDS: ReadonlyMap<number, ParamKind> = P;

/** pnames that only exist on WebGL 2 contexts. */
export const WEBGL2_ONLY_PNAMES: ReadonlySet<number> = new Set<number>([
  GL.COPY_READ_BUFFER_BINDING, GL.COPY_WRITE_BUFFER_BINDING, GL.PIXEL_PACK_BUFFER_BINDING, GL.PIXEL_UNPACK_BUFFER_BINDING,
  GL.TRANSFORM_FEEDBACK_BUFFER_BINDING, GL.UNIFORM_BUFFER_BINDING, GL.READ_FRAMEBUFFER_BINDING, // DRAW_FRAMEBUFFER_BINDING aliases FRAMEBUFFER_BINDING
  GL.FRAGMENT_SHADER_DERIVATIVE_HINT, GL.READ_BUFFER, GL.MAX_3D_TEXTURE_SIZE, GL.MAX_ARRAY_TEXTURE_LAYERS,
  GL.MAX_COLOR_ATTACHMENTS, GL.MAX_COMBINED_UNIFORM_BLOCKS, GL.MAX_DRAW_BUFFERS, GL.MAX_ELEMENTS_INDICES,
  GL.MAX_ELEMENTS_VERTICES, GL.MAX_FRAGMENT_INPUT_COMPONENTS, GL.MAX_FRAGMENT_UNIFORM_BLOCKS,
  GL.MAX_FRAGMENT_UNIFORM_COMPONENTS, GL.MAX_PROGRAM_TEXEL_OFFSET, GL.MIN_PROGRAM_TEXEL_OFFSET, GL.MAX_SAMPLES,
  GL.MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS, GL.MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS,
  GL.MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS, GL.MAX_UNIFORM_BUFFER_BINDINGS, GL.MAX_VARYING_COMPONENTS,
  GL.MAX_VERTEX_OUTPUT_COMPONENTS, GL.MAX_VERTEX_UNIFORM_BLOCKS, GL.MAX_VERTEX_UNIFORM_COMPONENTS,
  GL.UNIFORM_BUFFER_OFFSET_ALIGNMENT, GL.PACK_ROW_LENGTH, GL.PACK_SKIP_PIXELS, GL.PACK_SKIP_ROWS, GL.UNPACK_IMAGE_HEIGHT,
  GL.UNPACK_ROW_LENGTH, GL.UNPACK_SKIP_IMAGES, GL.UNPACK_SKIP_PIXELS, GL.UNPACK_SKIP_ROWS, GL.MAX_TEXTURE_LOD_BIAS,
  GL.MAX_CLIENT_WAIT_TIMEOUT_WEBGL, GL.MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS, GL.MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS,
  GL.MAX_ELEMENT_INDEX, GL.MAX_SERVER_WAIT_TIMEOUT, GL.MAX_UNIFORM_BLOCK_SIZE, GL.RASTERIZER_DISCARD,
  GL.TRANSFORM_FEEDBACK_ACTIVE, GL.TRANSFORM_FEEDBACK_PAUSED, GL.SAMPLER_BINDING, GL.TEXTURE_BINDING_2D_ARRAY,
  GL.TEXTURE_BINDING_3D, GL.TRANSFORM_FEEDBACK_BINDING, GL.VERTEX_ARRAY_BINDING,
  ...Array.from({ length: 16 }, (_, i) => GL.DRAW_BUFFER0 + i),
]);

/** Extension pnames and the WebGL extension that unlocks them. */
export const PNAME_EXTENSION: ReadonlyMap<number, string[]> = new Map<number, string[]>([
  [EXT_PNAME.MAX_TEXTURE_MAX_ANISOTROPY_EXT, ['EXT_texture_filter_anisotropic']],
  [EXT_PNAME.FRAGMENT_SHADER_DERIVATIVE_HINT_OES, ['OES_standard_derivatives']],
  [EXT_PNAME.VERTEX_ARRAY_BINDING_OES, ['OES_vertex_array_object']],
  [EXT_PNAME.MAX_COLOR_ATTACHMENTS_WEBGL, ['WEBGL_draw_buffers']],
  [EXT_PNAME.MAX_DRAW_BUFFERS_WEBGL, ['WEBGL_draw_buffers']],
  [EXT_PNAME.UNMASKED_VENDOR_WEBGL, ['WEBGL_debug_renderer_info']],
  [EXT_PNAME.UNMASKED_RENDERER_WEBGL, ['WEBGL_debug_renderer_info']],
  [EXT_PNAME.TIMESTAMP_EXT, ['EXT_disjoint_timer_query', 'EXT_disjoint_timer_query_webgl2']],
  [EXT_PNAME.GPU_DISJOINT_EXT, ['EXT_disjoint_timer_query', 'EXT_disjoint_timer_query_webgl2']],
  [EXT_PNAME.MAX_VIEWS_OVR, ['OVR_multiview2']],
  [EXT_PNAME.MAX_CLIP_DISTANCES_WEBGL, ['WEBGL_clip_cull_distance']],
  [EXT_PNAME.MAX_CULL_DISTANCES_WEBGL, ['WEBGL_clip_cull_distance']],
  [EXT_PNAME.MAX_COMBINED_CLIP_AND_CULL_DISTANCES_WEBGL, ['WEBGL_clip_cull_distance']],
  [EXT_PNAME.MAX_DUAL_SOURCE_DRAW_BUFFERS_WEBGL, ['WEBGL_blend_func_extended']],
  [EXT_PNAME.PROVOKING_VERTEX_WEBGL, ['WEBGL_provoking_vertex']],
  [EXT_PNAME.CLIP_ORIGIN_EXT, ['EXT_clip_control']],
  [EXT_PNAME.CLIP_DEPTH_MODE_EXT, ['EXT_clip_control']],
  [EXT_PNAME.POLYGON_OFFSET_CLAMP_EXT, ['EXT_polygon_offset_clamp']],
  [EXT_PNAME.POLYGON_MODE_WEBGL, ['WEBGL_polygon_mode']],
]);
